### ISSUE TITLE
Generate multiple entities at once from Dir

### ISSUE THREAD

**Issue by fasteddys** [EasyAbp/AbpHelper.CLI#185]
Hello, when we have several models/entities, is it possible to generate/run all/several entities at once.

For e.g. if we have dir with all my manually coded entities `C:\SchoolProject\MySourceEntites\*.cs` , how can we run a command like 

`abphelper generate crud C:\SchoolProject\MySourceEntites\*.cs  -d C:\SchoolProject\MyABPHelperFiles`

**Comment by gdlcf88** [comment]
Aggregates have independent directories; if we add this new usage, you still need to run the command for each directory. And, it's not hard to generate CRUD separately for the aggregate root and some other entities you want.

I think this change is not necessary. You are better to do it with batch scripts since we should keep the command simple. Anyway, thanks for your advice.
