### ISSUE TITLE
First use cli to generate a project, and then generate module under the project directory，cannot generate crud files with error:System.NotSupportedException: Unknown ABP project structure. 

### ISSUE THREAD

**Issue by indexlang** [EasyAbp/AbpHelper.CLI#201]
Conont reopen from #200 
Sorry, my problem description may not be clear. 
First use abp cli to generate a project, and then generate module under the project directory:
 `abp add-module CompanyName.ModuleA --new --add-to-solution-file` 
and then the project like
![image](https://user-images.githubusercontent.com/6028356/204846492-02eedffe-7c3e-44b2-a2ce-5f9106afdcf4.png)
there is no .Host.Shared.csproj.

**Comment by gdlcf88** [comment]
Do you mean generate CRUD for the added module projects?

AbpHelper determines a module solution type by finding the "*.Host.Shared.csproj" file since some older modules don't have the "Installer" project. Maybe we can check both the "*.Host.Shared.csproj" and "*.Installer.csproj" files for your case.

Do you want to create a PR for that?

**Comment by indexlang** [comment]
Okay, I'll do it after home office
